### ISSUE TITLE
Unnecessary line breaking when there are few votes

### ISSUE THREAD

**Issue by vitorhugods** [wireapp/poll-bot#16]
Currently on Wire Desktop, the vote count can be unnecessarily long, leading to break lines and making it hard to read the results at a first glance.
I _think_ the squares count per vote entry is equal to the number of participants, even though most of the participants didn't vote.

![grafik](https://user-images.githubusercontent.com/9389043/196703827-1832cdc5-691e-498e-9cb5-a98f8fc7a3d6.png)

We could just make the the square count equal the most voted option instead.

I'm adding this ticket as a placeholder so I don't forget, I'll raise a PR soon™

**Comment by LukasForst** [comment]
Either that or we remove this completely. Maybe just showing number of votes and emoji 🥇🥈🥉?

**Comment by vitorhugods** [comment]
> Either that or we remove this completely. Maybe just showing number of votes and emoji 🥇🥈🥉?

Vote count can still be useful. We use this for estimation in the Android team, and it's useful to know how the votes are spread-out.

**Comment by vitorhugods** [comment]
I opened a PR with a proposal for this.
